name: Test my workflow
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: gbalchev/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
